site_name: Internet Of Things (IoT) với ESP8266
site_url: https://esp8266.vn
site_description: ESP8266 Việt Nam
#theme: readthedocs
site_author: Tuan PM
theme_dir: readthedocshm
copyright: Copyright &copy; 2016 <a href="https://esp8266.vn">ESP8266 Viet Nam</a>
markdown_extensions:
    - toc:
        permalink: '#'
    - admonition
    - smarty
    - custom_span_class
repo_name: GitHub
repo_url: https://github.com/esp8266vn/esp8266.vn
google_analytics: ['UA-60470603-4', 'esp8266.vn']

# Page tree
pages:
  - Trang chủ:                      index.md
  - Nội dung:
    - Kiến thức cơ bản:
      - Tổng quan:                    introduction/introduction.md
      - Internet Of Things (IoT):     introduction/about-iot.md
      - ESP8266 & ESP8285:            introduction/about-esp8266.md
      - Các loại Module:              introduction/esp-module.md
      - Board phát triển:             introduction/board.md
      - Phần cứng & công cụ:          introduction/prepare.md
    - ESP8266 NONOS-SDK:
      - Giới thiệu:                   nonos-sdk/nonos-sdk.md
      - Cơ bản:
        - Cài đặt công cụ cần thiết:  nonos-sdk/basic/basic.md
        - Biên dịch dự án mẫu:        nonos-sdk/basic/compile-first-time.md
        - Bật tắt LED:                nonos-sdk/basic/blink-led.md
        - Nút nhấn:                   nonos-sdk/basic/button.md
        - UART:                       nonos-sdk/basic/uart.md
        - Makefile cho dự án phức tạp: nonos-sdk/basic/complex-makefile.md
        - Task:                       nonos-sdk/basic/task.md
        - Wifi:                       nonos-sdk/basic/wifi.md
        - ESPCONN:                    nonos-sdk/basic/espconn.md
        - MDNS:                       nonos-sdk/basic/mdns.md
        - NTP:                        nonos-sdk/basic/ntp.md
        - Lưu dữ liệu vào Flash:      nonos-sdk/basic/save-to-flash.md
      - Smartconfig:
        - ESP8266 Smartconfig:        nonos-sdk/smartconfig/smartconfig.md
        - Tại sao cần Smartconfig:    nonos-sdk/smartconfig/why-smartconfig.md
        - ESPTOUCH & AIRKISS:         nonos-sdk/smartconfig/esptouch.md
        - WPS:                        nonos-sdk/smartconfig/wps.md
      - MQTT:
        - Giao thức MQTT:             nonos-sdk/mqtt/what-is-mqtt.md
        - ESP8266 MQTT Client:        nonos-sdk/mqtt/mqtt-client.md
      - HTTP Client:
        - ESP8266 HTTP Client:        nonos-sdk/http-client/http-client.md
      - HTTP Server:
        - ESP8266 HTTP Server:        nonos-sdk/http-server/http-server.md
      - Firmware Over The Air:
        - FOTA:                       nonos-sdk/fota/fota.md
      - ESP Now:
        - ESP Now:                    nonos-sdk/esp-now/esp-now.md
      - ESP Mesh:
        - ESP Mesh:                   nonos-sdk/esp-mesh/esp-mesh.md
      - Các dự án:
        - Danh sách:                  nonos-sdk/projects/list.md

    - ESP8266 FreeRTOS-SDK:
      - Giới thiệu:                   freertos-sdk/freertos-sdk.md
      - Cơ bản:
        - Cài đặt công cụ cần thiết:  freertos-sdk/basic/introduction.md
        - Task cơ bản:                freertos-sdk/basic/basic-task.md
        - Software Timer:             freertos-sdk/basic/software-timer.md
        - Đồng bộ / trao đổi dữ liệu: freertos-sdk/basic/queue-semaphore-mutex.md
        - Task notification:          freertos-sdk/basic/task-notification.md
    - ESP8266 Arduino:
      - Giới thiệu:                   arduino/arduino.md
      - Cơ bản:
        - Cài đặt:                    arduino/basic/install.md
        - Digital:                    arduino/basic/digital.md
        - Analog:                     arduino/basic/analog.md
        - Thời gian & Delay:          arduino/basic/timming-delay.md
        - Serial:                     arduino/basic/serial.md
        - Progmem:                    arduino/basic/progmem.md
      - Thư viện:
        - ESP8266WiFi:                arduino/libraries/esp8266-wifi.md
        - ESP-API:                    arduino/libraries/esp-api.md
        - Ticker:                     arduino/libraries/ticker.md
        - EEPROM:                     arduino/libraries/eeprom.md
        - I2C (Thư viện Wire):        arduino/libraries/i2c.md
        - SPI:                        arduino/libraries/spi.md
        - Software Serial:            arduino/libraries/software-serial.md
        - mDNS và DNS-SD:             arduino/libraries/mdns-dnssd.md
        - SSDP:                       arduino/libraries/ssdp.md
        - DNS Server:                 arduino/libraries/dns-server.md
        - Servo:                      arduino/libraries/servo.md
        - Thư viện hữu ích khác:      arduino/libraries/others.md
      - Filesystem:
        - Flash Layout:               arduino/filesystem/flash-layout.md
      - Cập nhật Firmware (FOTA):
        - Giới thiệu OTA:             arduino/ota/arduino-fota.md
        - Sử dụng Arduino IDE:        arduino/ota/using-arduino-ide.md
        - Sử dụng trình duyệt:        arduino/ota/using-web-browser.md
        - Sử dụng HTTP Server:        arduino/ota/using-http-server.md
      - Phần cứng hỗ trợ:             arduino/arduino-esp8266-hardware.md
      - Các dự án:
        - Danh sách:                  arduino/projects/list.md
        - Smartconfig & react-native: arduino/projects/smartconfig-react-native.md
        - Smart Plug & Slack Bot:     arduino/projects/smartplug-slack.md
    - ESP8266 Micropython:
      - Giới thiệu:                   micropython/micropython.md
      - Cơ bản:
        - Cài đặt công cụ cần thiết:  micropython/basic/introduction.md

  - Các dự án:                      projects/list.md
  - Bản quyền:                      license.md
  - Đóng góp:                       contributor.md

